<a href="https://colab.research.google.com/github/Ragul-S-2025/ML/blob/main/Classification_Confusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import pandas as pd

In [51]:
data=pd.read_csv('/content/wine_quality_merged.csv')

In [52]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [53]:
data[["type"]].value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [54]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
type                    0
dtype: int64

In [55]:
x=data[["volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density"]]

In [56]:
x

,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density
0,0.70,0.00,1.9,0.076,11.0,34.0,0.99780
1,0.88,0.00,2.6,0.098,25.0,67.0,0.99680
2,0.76,0.04,2.3,0.092,15.0,54.0,0.99700
3,0.28,0.56,1.9,0.075,17.0,60.0,0.99800
4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780
...,...,...,...,...,...,...,...
6492,0.21,0.29,1.6,0.039,24.0,92.0,0.99114
6493,0.32,0.36,8.0,0.047,57.0,168.0,0.99490
6494,0.24,0.19,1.2,0.041,30.0,111.0,0.99254
6495,0.29,0.30,1.1,0.022,20.0,110.0,0.98869
6496,0.21,0.38,0.8,0.020,22.0,98.0,0.98941

In [57]:
y=data[["type"]]
y.head()

  type
0  red
1  red
2  red
3  red
4  red

In [58]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y)

In [59]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=200,   # number of trees
    random_state=42,
    n_jobs=-1 )

In [60]:
rf.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [61]:
y_pred = rf.predict(x_test)

In [62]:
y_pred

array(['white', 'white', 'white', ..., 'red', 'white', 'white'],
      dtype=object)

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report

In [64]:
confusion_matrix= confusion_matrix(y_test, y_pred)

In [65]:
confusion_matrix

array([[317,   3],
       [  5, 975]])

In [75]:

precision= precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
f1= f1_score(y_test, y_pred, average="weighted")

In [76]:
precision

0.9938653237933046

In [77]:
recall

0.9938461538461538

In [79]:
f1

0.9938525963518088

In [82]:
import pickle


file_name=("classfication.sav")


pickle.dump(rf,open(file_name,"wb"))


result=pickle.load(open(file_name,"rb"))

In [87]:
# Get user input
user_input = {}
user_input['volatile acidity'] = float(input('Enter volatile acidity: '))
user_input['citric acid'] = float(input('Enter citric acid: '))
user_input['residual sugar'] = float(input('Enter residual sugar: '))
user_input['chlorides'] = float(input('Enter chlorides: '))
user_input['free sulfur dioxide'] = float(input('Enter free sulfur dioxide: '))
user_input['total sulfur dioxide'] = float(input('Enter total sulfur dioxide: '))
user_input['density'] = float(input('Enter density: '))

# Convert to DataFrame
user_df = pd.DataFrame([user_input])

# Make prediction
prediction = result.predict(user_df)

# Display the prediction
print(f"The predicted wine type is: {prediction[0]}")

Enter volatile acidity: 45
Enter citric acid: 5
Enter residual sugar: 67
Enter chlorides: 876
Enter free sulfur dioxide: 67
Enter total sulfur dioxide: 876
Enter density: 876
The predicted wine type is: white

In [90]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,5))
sns.heatmap(user_df.iloc[:-3, :].T, annot=True, cmap="Blues", fmt=".2f")

ValueError: zero-size array to reduction operation fmin which has no identity