<a href="https://colab.research.google.com/github/Ragul-S-2025/ML/blob/main/GridCV_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing the Libraies
import numpy as np
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('/content/insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

grid = GridSearchCV(GradientBoostingRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'max_depth': [None, 10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             verbose=3)

In [11]:
from sklearn.model_selection import GridSearchCV

# Assuming 'grid' is your GridSearchCV object and has been fitted to the data
print("Best parameters:", grid.best_params_)

# Access the mean test score for the best parameters
best_index = grid.best_index_
best_r2_score = grid.cv_results_['mean_test_score'][best_index]
# Printing the best R² score
print("r2:",best_r2_score)

Best parameters: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}
r2: 0.7730800727526423

In [12]:
table=pd.DataFrame.from_dict(grid.cv_results_)
table.sort_values('rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
2,0.988744,0.058611,0.020586,0.007546,None,sqrt,1,5,100,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.789491,0.737779,0.806321,0.793607,0.738202,0.773080,0.029183,1
33,1.051276,0.266519,0.019571,0.003201,20,sqrt,1,2,200,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.772087,0.740815,0.795191,0.822708,0.733307,0.772822,0.033393,2
19,0.464887,0.009929,0.005925,0.000054,10,sqrt,1,5,200,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.798617,0.726884,0.801456,0.796484,0.731334,0.770955,0.034232,3
1,1.725116,0.326753,0.027708,0.010637,None,sqrt,1,2,200,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.775845,0.730314,0.801336,0.811933,0.734638,0.770813,0.033456,4
26,0.234658,0.006070,0.003904,0.000050,10,log2,1,5,100,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.788791,0.730670,0.803839,0.791439,0.739094,0.770767,0.029856,5
42,0.290172,0.015051,0.004917,0.000068,20,log2,1,5,100,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.780764,0.742336,0.792880,0.801735,0.735668,0.770677,0.026788,6
0,0.717994,0.084462,0.011394,0.003486,None,sqrt,1,2,100,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.781036,0.722766,0.805050,0.801457,0.733850,0.768832,0.034266,7
8,0.350997,0.016965,0.006734,0.000707,None,log2,1,2,100,"{'max_depth': None, 'max_features': 'log2', 'm...",0.777735,0.742828,0.802965,0.785866,0.732036,0.768286,0.026695,8
11,0.679883,0.098429,0.008760,0.000737,None,log2,1,5,200,"{'max_depth': None, 'max_features': 'log2', 'm...",0.793279,0.742212,0.792986,0.783344,0.726371,0.767638,0.027914,9
25,0.515557,0.017746,0.007004,0.000050,10,log2,1,2,200,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.767836,0.717658,0.809170,0.801001,0.741751,0.767483,0.034659,10
43,0.876012,0.215389,0.010951,0.002746,20,log2,1,5,200,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.782663,0.729722,0.800006,0.785788,0.738440,0.767324,0.027902,11
9,0.960232,0.223473,0.020259,0.006420,None,log2,1,2,200,"{'max_depth': None, 'max_features': 'log2', 'm...",0.769586,0.711146,0.816815,0.794725,0.743653,0.767185,0.037206,12
32,0.352768,0.007618,0.006486,0.000147,20,sqrt,1,2,100,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.781448,0.737585,0.802229,0.789036,0.722824,0.766624,0.030827,13
41,0.683167,0.017418,0.011508,0.001513,20,log2,1,2,200,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.774208,0.738310,0.791084,0.796482,0.732689,0.766555,0.026459,14
20,0.270645,0.054141,0.005576,0.002463,10,sqrt,2,2,100,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.781326,0.723150,0.800297,0.800412,0.727158,0.766469,0.034465,15
17,0.516928,0.013931,0.007561,0.001076,10,sqrt,1,2,200,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.782782,0.700615,0.808408,0.795340,0.743915,0.766212,0.039252,16
30,0.232662,0.014902,0.003861,0.000088,10,log2,2,5,100,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.779972,0.734439,0.788592,0.790323,0.736744,0.766014,0.025097,17
6,0.291724,0.009493,0.004760,0.000152,None,sqrt,2,5,100,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.780592,0.708774,0.797276,0.805092,0.734926,0.765332,0.037303,18
21,0.820567,0.131091,0.011897,0.003352,10,sqrt,2,2,200,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.785859,0.718638,0.790012,0.796253,0.735559,0.765264,0.031791,19
24,0.263037,0.008219,0.004543,0.000085,10,log2,1,2,100,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.779171,0.702924,0.814665,0.796537,0.732174,0.765094,0.041456,20
28,0.236746,0.009218,0.003979,0.000164,10,log2,2,2,100,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.786398,0.703475,0.801828,0.802175,0.730730,0.764921,0.040388,21
38,0.284622,0.015329,0.004722,0.000126,20,sqrt,2,5,100,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.781014,0.725134,0.787162,0.795285,0.733454,0.764410,0.029146,22
22,0.354708,0.051128,0.005269,0.001526,10,sqrt,2,5,100,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.778964,0.707574,0.792017,0.804861,0.738453,0.764374,0.036095,23
10,0.499849,0.064842,0.008381,0.004845,None,log2,1,5,100,"{'max_depth': None, 'max_features': 'log2', 'm...",0.772231,0.716750,0.811260,0.788857,0.729120,0.763644,0.035686,24
16,0.263603,0.011530,0.004824,0.000816,10,sqrt,1,2,100,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.766585,0.724684,0.793299,0.791822,0.741149,0.763508,0.027224,25
7,0.588543,0.017764,0.008039,0.000357,None,sqrt,2,5,200,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.777935,0.722594,0.785401,0.795743,0.734891,0.763313,0.029049,26
40,0.353437,0.020569,0.006376,0.000226,20,log2,1,2,100,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.771656,0.708282,0.805555,0.795883,0.731820,0.762639,0.037236,27
27,0.462468,0.010817,0.005819,0.000051,10,log2,1,5,200,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.775002,0.701082,0.808235,0.796630,0.731624,0.762515,0.040345,28
5,0.607798,0.014796,0.008207,0.000097,None,sqrt,2,2,200,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.782888,0.713740,0.787487,0.787809,0.740228,0.762430,0.030180,29
15,0.582200,0.016128,0.008183,0.000465,None,log2,2,5,200,"{'max_depth': None, 'max_features': 'log2', 'm...",0.772486,0.718352,0.792838,0.795843,0.732629,0.762429,0.031538,30
34,0.464578,0.055511,0.007684,0.003245,20,sqrt,1,5,100,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.773729,0.710181,0.793589,0.798104,0.736472,0.762415,0.033985,31
3,1.566131,0.436851,0.013534,0.004708,None,sqrt,1,5,200,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.774740,0.713503,0.796467,0.791615,0.734357,0.762136,0.032690,32
13,0.616906,0.021304,0.008376,0.000059,None,log2,2,2,200,"{'max_depth': None, 'max_features': 'log2', 'm...",0.775910,0.732543,0.783823,0.785118,0.731087,0.761696,0.024605,33
47,0.560906,0.034467,0.007459,0.000632,20,log2,2,5,200,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.768325,0.719151,0.776216,0.801263,0.741254,0.761242,0.028451,34
36,0.302005,0.019784,0.004974,0.000201,20,sqrt,2,2,100,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.776458,0.709589,0.790590,0.795225,0.732901,0.760953,0.033819,35
4,0.308029,0.020528,0.005038,0.000149,None,sqrt,2,2,100,"{'max_depth': None, 'max_features': 'sqrt', 'm...",0.775065,0.718236,0.789009,0.788061,0.733252,0.760724,0.029370,36
46,0.280200,0.008104,0.005805,0.001807,20,log2,2,5,100,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.778552,0.710544,0.795594,0.789818,0.726865,0.760275,0.034767,37
29,0.477594,0.031938,0.005914,0.000116,10,log2,2,2,200,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.779537,0.713971,0.791054,0.789724,0.725308,0.759919,0.033322,38
37,0.604491,0.025127,0.008174,0.000338,20,sqrt,2,2,200,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.772290,0.713179,0.792318,0.796668,0.724664,0.759824,0.034585,39
35,0.618696,0.046171,0.008103,0.000251,20,sqrt,1,5,200,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.755189,0.722835,0.793868,0.793431,0.727251,0.758515,0.030759,40
12,0.296203,0.015289,0.004995,0.000230,None,log2,2,2,100,"{'max_depth': None, 'max_features': 'log2', 'm...",0.770257,0.722555,0.777344,0.791208,0.724535,0.757180,0.028285,41
44,0.495043,0.066161,0.006777,0.003513,20,log2,2,2,100,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.758567,0.713444,0.783477,0.797030,0.731577,0.756819,0.031142,42
45,0.683939,0.115964,0.008138,0.000083,20,log2,2,2,200,"{'max_depth': 20, 'max_features': 'log2', 'min...",0.771034,0.717970,0.769817,0.798089,0.726606,0.756703,0.029987,43
23,0.481979,0.044894,0.005830,0.000113,10,sqrt,2,5,200,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.771797,0.698420,0.798838,0.787748,0.722239,0.755809,0.038852,44
14,0.287221,0.011647,0.004760,0.000056,None,log2,2,5,100,"{'max_depth': None, 'max_features': 'log2', 'm...",0.765452,0.709966,0.774439,0.791325,0.734622,0.755161,0.029154,45
31,0.455481,0.017071,0.005731,0.000056,10,log2,2,5,200,"{'max_depth': 10, 'max_features': 'log2', 'min...",0.767478,0.700698,0.770709,0.787911,0.738738,0.753107,0.030597,46
18,0.234340,0.008779,0.003944,0.000108,10,sqrt,1,5,100,"{'max_depth': 10, 'max_features': 'sqrt', 'min...",0.766789,0.678306,0.791181,0.783605,0.740146,0.752005,0.040802,47
39,0.573517,0.015165,0.007600,0.000093,20,sqrt,2,5,200,"{'max_depth': 20, 'max_features': 'sqrt', 'min...",0.767010,0.707195,0.772606,0.784370,0.728839,0.752004,0.029126,48

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:23
BMI:24
Children:4
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[19897.62527181]